@startuml

title __SERVICE's Class Diagram__\n

  namespace com.jue.meet {
    namespace service {
      class com.jue.meet.service.CloudService {
          {static} - H_TIME_WHAT : int
          - audio_iv_answer : ImageView
          - audio_iv_hangup : ImageView
          - audio_iv_hf : ImageView
          - audio_iv_photo : CircleImageView
          - audio_iv_recording : ImageView
          - audio_iv_small : ImageView
          - audio_ll_answer : LinearLayout
          - audio_ll_hangup : LinearLayout
          - audio_ll_hf : LinearLayout
          - audio_ll_recording : LinearLayout
          - audio_tv_status : TextView
          - callId : String
          - callTimer : int
          - disposable : Disposable
          - isCallOrReceiver : boolean
          - isCallTo : int
          - isDrag : boolean
          - isHF : boolean
          - isMove : boolean
          - isReceiverTo : int
          - isRecording : boolean
          - isSmallShowLocal : boolean
          - lpSmallView : LayoutParams
          - mFullAudioView : View
          - mFullVideoView : View
          - mHandler : Handler
          - mLastX : int
          - mLastY : int
          - mLocalView : SurfaceView
          - mRemoteView : SurfaceView
          - mSmallAudioView : View
          - mSmallTime : TextView
          - video_big_video : RelativeLayout
          - video_iv_photo : CircleImageView
          - video_ll_answer : LinearLayout
          - video_ll_hangup : LinearLayout
          - video_ll_info : LinearLayout
          - video_small_video : RelativeLayout
          - video_tv_name : TextView
          - video_tv_status : TextView
          - video_tv_time : TextView
          + onBind()
          + onClick()
          + onCreate()
          + onDestroy()
          + onMessageEvent()
          - createSmallAudioView()
          - goneAudioView()
          - goneVideoView()
          - initService()
          - initWindow()
          - linkCloudServer()
          - parsingImMessage()
          - pushBitmap()
          - pushSystem()
          - saveAudioRecord()
          - saveNewFriend()
          - saveVideoRecord()
          - updateVideoView()
          - updateWindowInfo()
      }
    }
  }
  

  com.jue.meet.service.CloudService .up.|> android.view.View.OnClickListener
  com.jue.meet.service.CloudService -up-|> android.app.Service
  com.jue.meet.service.CloudService o-- com.jue.framework.manager.MediaPlayerManager : mAudioCallMedia
  com.jue.meet.service.CloudService o-- com.jue.framework.manager.MediaPlayerManager : mAudioHangupMedia


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
