@startuml

title __GSON's Class Diagram__\n

  namespace com.jue.framework {
    namespace gson {
      class com.jue.framework.gson.TextBean {
          - msg : String
          - type : String
          + getMsg()
          + getType()
          + setMsg()
          + setType()
      }
    }
  }
  

  namespace com.jue.framework {
    namespace gson {
      class com.jue.framework.gson.TokenBean {
          - code : int
          - token : String
          - userId : String
          + getCode()
          + getToken()
          + getUserId()
          + setCode()
          + setToken()
          + setUserId()
      }
    }
  }
  

  namespace com.jue.framework {
    namespace gson {
      class com.jue.framework.gson.VoiceBean {
          - bg : int
          - ed : int
          - ls : boolean
          - sn : int
          - ws : List<WsBean>
          + getBg()
          + getEd()
          + getSn()
          + getWs()
          + isLs()
          + setBg()
          + setEd()
          + setLs()
          + setSn()
          + setWs()
      }
    }
  }
  

  namespace com.jue.framework {
    namespace gson {
      class com.jue.framework.gson.VoiceBean.WsBean {
          - bg : int
          - cw : List<CwBean>
          + getBg()
          + getCw()
          + setBg()
          + setCw()
      }
    }
  }
  

  namespace com.jue.framework {
    namespace gson {
      class com.jue.framework.gson.VoiceBean.WsBean.CwBean {
          - sc : double
          - w : String
          + getSc()
          + getW()
          + setSc()
          + setW()
      }
    }
  }
  

  com.jue.framework.gson.VoiceBean +-down- com.jue.framework.gson.VoiceBean.WsBean
  com.jue.framework.gson.VoiceBean.WsBean +-down- com.jue.framework.gson.VoiceBean.WsBean.CwBean


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
