@startuml

title __MEET's Class Diagram__\n

  namespace com.jue.meet {
    class com.jue.meet.MainActivity {
        - disposable : Disposable
        - firstClick : long
        - iv_chat : ImageView
        - iv_me : ImageView
        - iv_square : ImageView
        - iv_star : ImageView
        - ll_chat : LinearLayout
        - ll_me : LinearLayout
        - ll_square : LinearLayout
        - ll_star : LinearLayout
        - mChatTransaction : FragmentTransaction
        - mMeTransaction : FragmentTransaction
        - mSquareTransaction : FragmentTransaction
        - mStarTransaction : FragmentTransaction
        - tv_chat : TextView
        - tv_me : TextView
        - tv_square : TextView
        - tv_star : TextView
        + AppExit()
        + onAttachFragment()
        + onBackPressed()
        + onClick()
        + onMessageEvent()
        # onCreate()
        # onDestroy()
        - checkMainTab()
        - checkToken()
        - createToken()
        - createUploadDialog()
        - hideAllFragment()
        - initFragment()
        - initView()
        - parsingCloudToken()
        - requestPermiss()
        - showFragment()
        - startCloudService()
    }
  }
  

  com.jue.meet.MainActivity .up.|> android.view.View.OnClickListener
  com.jue.meet.MainActivity -up-|> com.jue.framework.base.BaseUIActivity
  com.jue.meet.MainActivity o-- com.jue.meet.fragment.ChatFragment : mChatFragment
  com.jue.meet.MainActivity o-- com.jue.meet.fragment.MeFragment : mMeFragment
  com.jue.meet.MainActivity o-- com.jue.meet.fragment.SquareFragment : mSquareFragment
  com.jue.meet.MainActivity o-- com.jue.meet.fragment.StarFragment : mStarFragment
  com.jue.meet.MainActivity o-- com.jue.framework.view.DialogView : mUploadView


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
