@startuml

title __CLOUD's Class Diagram__\n

  namespace com.jue.framework {
    namespace cloud {
      class com.jue.framework.cloud.CloudManager {
          {static} + CLOUD_KEY : String
          {static} + CLOUD_SECRET : String
          {static} + MSG_IMAGE_NAME : String
          {static} + MSG_LOCATION_NAME : String
          {static} + MSG_TEXT_NAME : String
          {static} + TOKEN_URL : String
          {static} + TYPE_ADD_FRIEND : String
          {static} + TYPE_ARGEED_FRIEND : String
          {static} + TYPE_TEXT : String
          {static} + callAudioHangup : String
          {static} + callAudioPath : String
          - iSendMessageCallback : ISendMessageCallback
          {static} - mInstnce : CloudManager
          - sendImageMessageCallback : SendImageMessageCallback
          + acceptCall()
          + changeCallMediaType()
          + connect()
          + disconnect()
          + getConversationList()
          + getHistoryMessages()
          {static} + getInstance()
          + getRemoteHistoryMessages()
          + hangUpCall()
          + initCloud()
          + isConnect()
          + isVoIPEnabled()
          + logout()
          + sendImageMessage()
          + sendLocationMessage()
          + sendTextMessage()
          + setConnectionStatusListener()
          + setEnableLocalAudio()
          + setEnableLocalVideo()
          + setEnableSpeakerphone()
          + setOnReceiveMessageListener()
          + setReceivedCallListener()
          + setVoIPCallListener()
          + startAudioCall()
          + startAudioRecording()
          + startCall()
          + startVideoCall()
          + stopAudioRecording()
          + switchCamera()
          - CloudManager()
          - sendConnectStatus()
          - sendTextMessage()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
