@startuml

title __UTILS's Class Diagram__\n

  namespace com.jue.framework {
    namespace utils {
      class com.jue.framework.utils.AnimUtils {
          {static} + rotation()
      }
    }
  }
  

  namespace com.jue.framework {
    namespace utils {
      class com.jue.framework.utils.CommonUtils {
          {static} + isEmpty()
      }
    }
  }
  

  namespace com.jue.framework {
    namespace utils {
      class com.jue.framework.utils.LanguaueUtils {
          {static} + SYS_LANGUAGE : int
          {static} + updateLanguaue()
      }
    }
  }
  

  namespace com.jue.framework {
    namespace utils {
      class com.jue.framework.utils.LogUtils {
          {static} - mSimpleDateFormat : SimpleDateFormat
          {static} + e()
          {static} + i()
          {static} + writeToFile()
      }
    }
  }
  

  namespace com.jue.framework {
    namespace utils {
      class com.jue.framework.utils.SHA1 {
          {static} + sha1()
      }
    }
  }
  

  namespace com.jue.framework {
    namespace utils {
      class com.jue.framework.utils.SpUtils {
          - editor : Editor
          {static} - mInstance : SpUtils
          - sp : SharedPreferences
          + deleteKey()
          + getBoolean()
          {static} + getInstance()
          + getInt()
          + getString()
          + initSp()
          + putBoolean()
          + putInt()
          + putString()
          - SpUtils()
      }
    }
  }
  

  namespace com.jue.framework {
    namespace utils {
      class com.jue.framework.utils.SystemUI {
          {static} + fixSystemUI()
      }
    }
  }
  

  namespace com.jue.framework {
    namespace utils {
      class com.jue.framework.utils.TimeUtils {
          {static} + formatDuring()
          {static} + formatTime()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
